INSERT INTO Person (Name, Nickname, Age, Height, City, FavoriteColor)
VALUES ('Andrew', 'WPM', 25, 175, 'Irving', 'Aquamarine')
, ('Sean', 'Captain Bad Programmer', 24, 183, 'LA', 'Orange')
, ('Austin', 'Saint Austin of DevMountain', 23, 168, 'Orange County', 'Blue')
, ('Josh', 'TripleS', 30, 182, 'Lemoore', 'Green')
, ('Hunter', 'EDM Hunter', 18, 185, 'San Diego', 'Purple')